#+TITLE: HCAPI3
#+AUTHOR: Melanie Bacou
#+EMAIL: mel@mbacou.com
#+DATE: {{{modification-time(%Y-%m-%d)}}}

#+OPTIONS: H:2 num:1 toc:2 \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+LaTeX_CLASS: mel-article
#+STARTUP: indent showstars

HarvestChoice Data Services v3: Access HarvestChoice 10km Spatial Layers for sub-Saharan Africa.

Port of HarvestChoice data API to an OpenCPU server at http://hcapi.harvestchoice.org/ocpu/library/hcapi3. More about HarvestChoice spatial datasets for sub-Saharan Africa at http://harvestchoice.org/data/. To view this data in your browser visit [[http://apps.harvestchoice.org/mappr][HarvestChoice MAPPR]].

Currently this R package cannot be installed locally. Instead all data access methods are made available through a REST API (credits to [[http://github.com/jeroenooms/opencpu][OpenCPU]]). HTTP POST requests may be sent using any REST-compatible client (e.g. cURL). Sample requests using cURL at the command line, in JavaScript, as well as in R and STATA are provided in the package documentation.

** Overview

The package documentation is at http://harvestchoice.github.io/hc-api3.

HTTP POST requests may be tested interactively at http://hcapi.harvestchoice.org/ocpu/. To test requests in the console, use the following =curl= syntax. Arguments may be passed as well-structured json array with curl =-H Content-Type:application/json= flag or more directly as URL arguments using =-d 'param1="value1"&param2="value2"= construct. See a few examples below.


** Updates

*2015.04.22*: combined =getPlot()= and =genPlot()= into only one =genPlot()= method that can generate multiple plots at once.

*2015.01.22*: allow filtering variables across multiple country ISO3 codes.

*2014.12.18*: added a new argument =as.class=c("data.table", "list")= to =getLayer()= to allow control on the structure of the generated JSON response.

*2014.11.11*: added a new method =classify()= for "on-the-fly" domain classification (aka. Spatial Targeting Tool) documented at http://hcapi.harvestchoice.org/ocpu/library/hcapi3/man/classify/pdf.

#+BEGIN_SRC sh
# Sample request
$ time curl http://hcapi.harvestchoice.org/ocpu/library/hcapi3/R/classify/json \
 -d '{"var" : ["whea_h", "AEZ16_CLAS"], "by" : {"AEZ16_CLAS": "Tropic - warm / semiarid", "PD05_RUR" : [60, 100], "TT_20K" : [0, 5]}}' \
 -X POST -H "Content-Type:application/json"
#+END_SRC

#+BEGIN_SRC json
[
    {
        "TT_20K": "(0,5]",
        "whea_h": 111336,
        "AEZ16_CLAS": "Tropic - warm / semiarid"
    },
    {
        "whea_h": 26446,
        "AEZ16_CLAS": "Tropic - warm / semiarid"
    },
    {
        "PD05_RUR": "(60,100]",
        "TT_20K": "(0,5]",
        "whea_h": 14437,
        "AEZ16_CLAS": "Tropic - warm / semiarid"
    },
    {
        "PD05_RUR": "(60,100]",
        "whea_h": 6201,
        "AEZ16_CLAS": "Tropic - warm / semiarid"
    }
]

real    0m1.100s
user    0m0.015s
sys     0m0.015s
#+END_SRC

*2014.11.10*: changed data storage from sqlite database to persistent Rserve session (faster). rApache and RSQLite seemed to have a library conflict (logged bug [[https://github.com/rstats-db/RSQLite/issues/60#issuecomment-62497666][#issuecomment-62497666]]).

*2014.11.10*: added a new method =getLayerWKT()= to support point/polygon summaries.

#+BEGIN_SRC sh
# Sample request with a few points
$ time curl http://hcapi.harvestchoice.org/ocpu/library/hcapi3/R/getLayerWKT/json \
 -d '{"var" : ["whea_h", "AEZ16_CLAS"], "wkt" : "MULTIPOINT((35.69319860636820607 -3.91388197570256979), (35.47695932281013853 -4.34541210453119486), (36.61014339398586515 -6.19304393571206635), (36.47436786329777902 -5.51879978940470828))"}' \
 -X POST -H "Content-Type:application/json"
#+END_SRC

#+BEGIN_SRC json
[
    {
        "CELL5M": 4987879,
        "ISO3": "TZA",
        "ADM0_NAME": "United Republic of Tanzania",
        "ADM1_NAME_ALT": "Dodoma",
        "ADM2_NAME_ALT": "Kongwa",
        "X": 36.625,
        "Y": -6.2083,
        "whea_h": 0,
        "AEZ16_CLAS": "Tropic - warm / semiarid"
    },
    {
        "CELL5M": 4866908,
        "ISO3": "TZA",
        "ADM0_NAME": "United Republic of Tanzania",
        "ADM1_NAME_ALT": "Manyara",
        "ADM2_NAME_ALT": "Babati",
        "X": 35.7083,
        "Y": -3.875,
        "whea_h": 0,
        "AEZ16_CLAS": "Tropic - warm / semiarid"
    },
    {
        "CELL5M": 4892825,
        "ISO3": "TZA",
        "ADM0_NAME": "United Republic of Tanzania",
        "ADM1_NAME_ALT": "Manyara",
        "ADM2_NAME_ALT": "Hanang",
        "X": 35.4583,
        "Y": -4.375,
        "whea_h": 148,
        "AEZ16_CLAS": "Tropic - cool / subhumid"
    },
    {
        "CELL5M": 4953317,
        "ISO3": "TZA",
        "ADM0_NAME": "United Republic of Tanzania",
        "ADM1_NAME_ALT": "Manyara",
        "ADM2_NAME_ALT": "Kiteto",
        "X": 36.4583,
        "Y": -5.5417,
        "whea_h": 0,
        "AEZ16_CLAS": "Tropic - cool / semiarid"
    }
]


real    0m2.660s
user    0m0.000s
sys     0m0.030s
#+END_SRC

